name: Integration Tests
on: push
jobs:
  go-tests:
    name: Run Go Integration Tests
    runs-on: ubuntu-latest
    container: eshijii/terraform-tools:latest
    steps:
      - uses: actions/checkout@v1
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - name: Run Go Tests
        working-directory: test
        run: go test -v
